services:
  db:
    image: postgres:17
    container_name: post-comment-system-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ozon_test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_postgres:
    build: .
    container_name: app-postgres
    depends_on:
      db:
        condition: service_healthy
    profiles: ["postgres"]
    environment:
      STORAGE_TYPE: "postgres"
      POSTGRES_DSN: "postgres://postgres:postgres@db:5432/ozon_test?sslmode=disable"
    ports:
      - "8080:8080"

  app_memory:
    build: .
    container_name: app-memory
    depends_on:
      db:
        condition: service_healthy
    profiles: ["memory"]
    environment:
      STORAGE_TYPE: "memory"
    ports:
      - "8080:8080"

volumes:
  pg_data:
