// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string  `json:"id"`
	Content  string  `json:"content"`
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Query struct {
}
