// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	Author    string     `json:"author"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	Author          string    `json:"author"`
	CommentsEnabled bool      `json:"commentsEnabled"`
	CreatedAt       time.Time `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
